id: motion-status.ui
version: 1.0
type: object
description: UI components for motion detection system
bindsTo: motion.state
components:
  - type: component
    fields:
      - name: isMoving
        type: boolean
        description: Current motion state
      - name: controlMode
        type: string
        description: Current control mode
      - name: varianceThreshold
        type: number
        description: Motion detection threshold
    submitEvent: motion-status-update

  - type: component
    fields:
      - name: controlMode
        type: string
        description: Current control mode
      - name: varianceThreshold
        type: number
        description: Motion detection threshold
        format: slider
        min: 0.1
        max: 5.0
        step: 0.1
    submitEvent: update-motion-settings

  - type: component
    fields:
      - name: sensitivity
        type: number
        description: Motion detection sensitivity
        format: slider
        min: 0
        max: 100
        step: 1
    submitEvent: update-motion-sensitivity

views:
  - path: /
    layout: main

metadata:
  createdBy: system
  tags: [motion, ui] 